name: Daily Commit

on:
  schedule:
    - cron: "30 5 * * *"  # Runs daily at 05:30 UTC (Change as needed)
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File (lisa.miranda@gramener.com)
        run: |
          echo "Last run: $(date)" > last_run.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "lisa.miranda@gramener.com"
          git add last_run.txt
          git commit -m "Daily update $(date)"
          git push
